### ISSUE TITLE
There is only one piece of code that throws a DeadlineSoonException.May I ask what is the cause?

### ISSUE THREAD

**Issue by twomiao** [pheanstalk/pheanstalk#195]
PHP Fatal error:  Uncaught Pheanstalk\Exception\DeadlineSoonException in /home/Worker/vendor/pda/pheanstalk/src/Command/ReserveCommand.php:25
Stack trace:
#0 /home/Worker/vendor/pda/pheanstalk/src/Connection.php(114): Pheanstalk\Command\ReserveCommand->parseResponse('DEADLINE_SOON', NULL)
#1 /home/Worker/vendor/pda/pheanstalk/src/Pheanstalk.php(369): Pheanstalk\Connection->dispatchCommand(Object(Pheanstalk\Command\ReserveCommand))
#2 /home/Worker/vendor/pda/pheanstalk/src/Pheanstalk.php(255): Pheanstalk\Pheanstalk->dispatch(Object(Pheanstalk\Command\ReserveCommand))
#3 /home/Worker/app/test/stalk.php(31): Pheanstalk\Pheanstalk->reserve()
#4 {main}
  thrown in /home/Worker/vendor/pda/pheanstalk/src/Command/ReserveCommand.php on line 25
### 测试代码：
```$pheanstalk = Pheanstalk::create('127.0.0.1');

try {
    while (true) {
        $job = $pheanstalk
            ->watch('Order')
            ->ignore('default')
            ->reserve();

        $payload = $job->getData();
        if ($job->getId() > 0) {
            print_r($payload . PHP_EOL);
            sleep(2);
            var_dump(json_decode($payload, true));
        }
    }
} catch (ConnectionException $e) {
    exit("[ ERROR ] => Beanstalk could not connect to the server.\n");
}
```

**Comment by dontub** [comment]
https://github.com/beanstalkd/beanstalkd/wiki/FAQ#what-does-deadline_soon-mean should answer your question.

**Comment by SamMousa** [comment]
Yes this is normal, you are not releasing the jobs, so at some point your reservation will expire.

**Comment by SamMousa** [comment]
Correct

**Comment by twomiao** [comment]
How to solve it, don't throw this exception?
 
 

 ------------------ 原始邮件 ------------------
  发件人: "Sam"<notifications@github.com>; 
 发送时间: 2019年10月11日(星期五) 下午4:28
 收件人: "pheanstalk/pheanstalk"<pheanstalk@noreply.github.com>; 
 抄送: "995200452"<995200452@qq.com>; "Author"<author@noreply.github.com>; 
 主题: Re: [pheanstalk/pheanstalk] Is this abnormal DeadlineSoonExceptionwhat is the cause? Can explain in detail, thank you (#195)

 

 
Closed #195.

**Comment by SamMousa** [comment]
No, solve it by catching it... and handling it properly.
It is an exception thrown in the reserve command, so you should be able to easily handle it and extend your reservation(s).

You can also prevent this exception by actually removing jobs that you have completed from the queue.

**Comment by twomiao** [comment]
For example, in this case: the mail is taken out of the queue and the mail is sent successfully. Then I delete the task, but still throw this exception.

public function doJob(): bool     {         $connection = new Connection('127.0.0.1', 11300, 2, true);         $beansClient = new BeansClient($connection);         try {             $job = $beansClient->watchTube('MailerBox')                 ->reserve(3);             $data = json_decode($job->payload, true);             if (!empty($data)) {                 if (MailBox::send($data)) {                     //todo:: 邮件发送逻辑 //                    (new MailerService())->log($data, MailStats::SENT_SUCCESS); # 发送成功记录一条日志                     Console::println(date('Y-m-d ')." 异步邮件已发送 -> 内容:".$data['body']                         ,ColorText::FG_CYAN);                     // 删除队列中的已发送邮件                     $job->delete();                     Console::println(date('Y-m-d ')." 异步队列中删除 -> 内容:".$data['to']                         ,ColorText::FG_RED);                     return true;                 } //                (new MailerService())->log($data, MailStats::SENT_ERROR); # 发送失败记录日志             }         }         catch (\Exception $e) {             /**              * 1. 异常必须捕捉,报错会不断重启Jober              * 2. 记录到日志文件              */ //            Log::error("异常原因:".$e->getMessage());         }         return false;     }











------------------ 原始邮件 ------------------
发件人: "Sam"<notifications@github.com>; 
发送时间: 2019年10月11日(星期五) 下午5:26
收件人: "pheanstalk/pheanstalk"<pheanstalk@noreply.github.com>; 
抄送: "995200452"<995200452@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [pheanstalk/pheanstalk] Is this abnormal DeadlineSoonExceptionwhat is the cause? Can explain in detail, thank you (#195)




No, solve it by catching it... and handling it properly.
 It is an exception thrown in the reserve command, so you should be able to easily handle it and extend your reservation(s).
 
You can also prevent this exception by actually removing jobs that you have completed from the queue.
