### ISSUE TITLE
Help with error NOT_FOUND

### ISSUE THREAD

**Issue by rbruhn** [pheanstalk/pheanstalk#245]
Laravel 9 using Homestead.

This isn't a bug with Pheanstalk. Only hoping someone might lead me in the direction to fix what's happening.
I'm running a VM using homestead on my local computer. I have two separate directories on Windows holding the same branches of code. One to hold the main code branch, and the other for more experimental things:

mysite.test 
dev.mysite.test

I typically reload supervisor to load the queues depending on the code I'm working with. Below are the dev queues and error I'm receiving. I also added the configuration. The only differences between the two sites are APP_DOMAIN,  APP_KEY, the directories, and the name of the tubes used in Beanstalk.

Everything works fine on mysite.test, No errors.
Errors only appears when working on dev.mysite.test
While working on dev.mysite.test, all the tubes are processed. Everything still works...I just keeping getting this repeated error filling up the logs. The errors only occur when the tubes are processing a job.

Would appreciate any help that can be offered to track this down.

```
LARAVEL_QUEUE_DRIVER=beanstalkd

QUEUE_EVENT_TUBE=devevent
QUEUE_EXPORT_TUBE=devexport

```

```
[program:devevent]
process_name=%(program_name)s_%(process_num)02d
directory=/home/vagrant/sites/devmysite
command=php artisan queue:work beanstalkd --force --queue=devevent --tries=3
stdout_logfile=/var/log/supervisor/dev/devevent.log
redirect_stderr=true
logfile_maxbytes=50MB
logfile_backups=1
autostart=true
autorestart=true
user=vagrant
numprocs=1

[program:devexport]
process_name=%(program_name)s_%(process_num)02d
directory=/home/vagrant/sites/devmysite
command=php artisan queue:work beanstalkd --force --queue=devexport --tries=3
stdout_logfile=/var/log/supervisor/dev/devexport.log
redirect_stderr=true
logfile_maxbytes=50MB                           
logfile_backups=1
autostart=true
autorestart=true
user=vagrant
numprocs=1
```

```
[2022-08-16 13:13:30] dev.ERROR: Server reported NOT_FOUND {"exception":"[object] (Pheanstalk\\Exception\\ServerException(code: 0): Server reported NOT_FOUND at /home/vagrant/sites/biospexDev/vendor/pda/pheanstalk/src/YamlResponseParser.php:39)
[stacktrace]
#0 /home/vagrant/sites/biospexDev/vendor/pda/pheanstalk/src/Connection.php(114): Pheanstalk\\YamlResponseParser->parseResponse()
#1 /home/vagrant/sites/biospexDev/vendor/pda/pheanstalk/src/Pheanstalk.php(369): Pheanstalk\\Connection->dispatchCommand()
#2 /home/vagrant/sites/biospexDev/vendor/pda/pheanstalk/src/Pheanstalk.php(286): Pheanstalk\\Pheanstalk->dispatch()
#3 /home/vagrant/sites/biospexDev/vendor/laravel/framework/src/Illuminate/Queue/Jobs/BeanstalkdJob.php(91): Pheanstalk\\Pheanstalk->statsJob()
#4 /home/vagrant/sites/biospexDev/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(531): Illuminate\\Queue\\Jobs\\BeanstalkdJob->attempts()
#5 /home/vagrant/sites/biospexDev/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(456): Illuminate\\Queue\\Worker->markJobAsFailedIfWillExceedMaxAttempts()
#6 /home/vagrant/sites/biospexDev/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(433): Illuminate\\Queue\\Worker->handleJobException()
#7 /home/vagrant/sites/biospexDev/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(379): Illuminate\\Queue\\Worker->process()
#8 /home/vagrant/sites/biospexDev/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(173): Illuminate\\Queue\\Worker->runJob()
#9 /home/vagrant/sites/biospexDev/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(150): Illuminate\\Queue\\Worker->daemon()
#10 /home/vagrant/sites/biospexDev/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(134): Illuminate\\Queue\\Console\\WorkCommand->runWorker()
#11 /home/vagrant/sites/biospexDev/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Illuminate\\Queue\\Console\\WorkCommand->handle()
#12 /home/vagrant/sites/biospexDev/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#13 /home/vagrant/sites/biospexDev/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#14 /home/vagrant/sites/biospexDev/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod()
#15 /home/vagrant/sites/biospexDev/vendor/laravel/framework/src/Illuminate/Container/Container.php(651): Illuminate\\Container\\BoundMethod::call()
#16 /home/vagrant/sites/biospexDev/vendor/laravel/framework/src/Illuminate/Console/Command.php(139): Illuminate\\Container\\Container->call()
#17 /home/vagrant/sites/biospexDev/vendor/symfony/console/Command/Command.php(308): Illuminate\\Console\\Command->execute()
#18 /home/vagrant/sites/biospexDev/vendor/laravel/framework/src/Illuminate/Console/Command.php(124): Symfony\\Component\\Console\\Command\\Command->run()
#19 /home/vagrant/sites/biospexDev/vendor/symfony/console/Application.php(998): Illuminate\\Console\\Command->run()
#20 /home/vagrant/sites/biospexDev/vendor/symfony/console/Application.php(299): Symfony\\Component\\Console\\Application->doRunCommand()
#21 /home/vagrant/sites/biospexDev/vendor/symfony/console/Application.php(171): Symfony\\Component\\Console\\Application->doRun()
#22 /home/vagrant/sites/biospexDev/vendor/laravel/framework/src/Illuminate/Console/Application.php(102): Symfony\\Component\\Console\\Application->run()
#23 /home/vagrant/sites/biospexDev/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(129): Illuminate\\Console\\Application->run()
#24 /home/vagrant/sites/biospexDev/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle()
#25 {main}
"} 
```

**Comment by SamMousa** [comment]
I think this is an issue in the illuminate/queue package not this one; or it is in your code.
What is happening is that there is an exception somewhere after which the library you're using tries to `statsJob` on the job. But the job no longer exists.
It could be that you're removing the job somewhere in its handler?

**Comment by rbruhn** [comment]
I've taken it down to just the "event" tube. That tube processes event jobs that broadcast using soketi. I'm not removing the job anywhere. Typing a command (ocr:poll), dispatching the job, and simply broadcasting a string still causes the error. However, no error on the normal site using the same code.
It's baffling me. I didn't think it was Pheanstalk. It has to be something else because it works normally on the regular domain. It seems to only happen on the subdomain, even using the same code.

Anyway, I will close this. Was simply wondering if it happened before. Thank you.

**Comment by rbruhn** [comment]
Just updating in case someone comes along. The issue was caused by using dusterio/laravel-plain-sqs
Once removed, everything worked correctly.
